### PR TITLE
Fix UnicodeDecodeError by reading README.md with UTF-8 encoding in se…

### PR DESCRIPTION
**Pull request by nitrohero**
…tup.py

- Updated setup.py to read the README.md file with UTF-8 encoding.
- This change prevents UnicodeDecodeError caused by non-ASCII characters in README.md.
- Ensures compatibility across different environments and proper rendering of the long description on PyPI.

### CODE REVIEW

**Comment by nitrohero** [comment]
added Missing Contributor License Agreement!

**Comment by ashwinb** [comment]
Can you tell us in what environment setup.py caused an error?

**Review by KryslynnB — COMMENTED** [review]
approved

**Comment by ashwinb** [comment]
Not enough detail as to when the current setup failed. We have not heard any other reports. Closing...

**Pull request closed without merging**
