### PR TITLE
Fix path resolving

### PR DESCRIPTION
**Pull request by danielhanchen**
Some fixes to join strings for file paths

### CODE REVIEW

**Comment by Ashkar999** [comment]
> Some fixes to join strings for file paths

**Review by Ashkar999 — APPROVED** [review]

**Comment by Ashkar999** [comment]
> > Some fixes to join strings for file paths
> 
>

**Comment by danielhanchen** [comment]
Oh whoops I'll do the CLA thingo

**Review by Ashkar999 — APPROVED** [review]

**Comment by danielhanchen** [comment]
Ok just did the CLA!

**Comment by ashwinb** [comment]
I don't think this is needed. `THIS_DIR` is of type `pathlib.Path` which overloads the "/" operator correctly. Can you show the precise failure?

**Review by ashwinb — CHANGES_REQUESTED** [review]
As commented, please describe the failure and when it happens. It should not be happening.

**Comment by danielhanchen** [comment]
Oh actually - it seems like I overrided  `THIS_DIR` with the actual directory in a Colab, and did not use `pathlib.Path`

**Comment by ashwinb** [comment]
Ok cool, closing this then.

**Pull request closed without merging**
