### PR TITLE
download.sh to use curl and chunk downloads of 405b models

### PR DESCRIPTION
**Pull request by samuelselvan**
The 405b model file sizes are too big to be downloaded in single chunk by cloudfront. So chunking and merging them manually

### CODE REVIEW

**Review by fbnav — APPROVED** [review]

**Comment by pmysl** [comment]
PTH files for the variants `meta-llama-3.1-405b-instruct-mp16` and `meta-llama-3.1-405b-mp16` are smaller than 50 GiB, so they don't need to be chunked

**Comment by traderjohnd** [comment]
about how many of these "chunked" files are downloaded that are about 50,066,702 KB's (50mb) for the 405b model?  (ie. consolidated.00.pth, consolidated.01.pth etc.)  Is roughly 20 correct? (1GB)

**Comment by samuelselvan** [comment]
Yes 50GB was the limit. 25GB is actually was the recommended sweet spot for the chunks.

**Comment by samuelselvan** [comment]
@traderjohnd it varies. meta-llama-3.1-405b-instruct-mp16 has 16 47.7GiB files.

**Pull request merged**
