### PR TITLE
Rename models -> llama_models

### PR DESCRIPTION
**Pull request by ashwinb**
This idiosyncrasy causes a lot of unnecessary annoyances down the line. It is a pretty standard practice to have the package name be the exact sub-directory within the repository.

### CODE REVIEW

**Review by raghotham — CHANGES_REQUESTED** [review]
Need to make sure model card URLs don’t break

**Comment by ashwinb** [comment]
@raghotham where are these model card URLs referenced btw? from the README or directly outside too? 

if I restore those with appropriate symlinks, would that be OK?

**Comment by ashwinb** [comment]
Added a symlink for models -> llama_models so no URL is invalidated.

**Comment by ashwinb** [comment]
https://github.com/meta-llama/llama-models/pull/201 is better I think as an option.

**Pull request closed without merging**
